CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL,
  "email" varchar(50) NOT NULL,
  "password" char(8) NOT NULL,
  "age" smallint NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20)
);

CREATE TABLE "user_roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "role_id" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "description" varchar(30) NOT NULL,
  "level_id" int NOT NULL,
  "teacher_id" int NOT NULL
);

CREATE TABLE "teachers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL
);

CREATE TABLE "levels" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL
);

CREATE TABLE "course_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_id" int NOT NULL,
  "url" varchar(50) NOT NULL,
  "categori_id" int NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL
);

ALTER TABLE "user_roles" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("level_id") REFERENCES "levels" ("id");

ALTER TABLE "course_video" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("id") REFERENCES "teachers" ("user_id");

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher_id") REFERENCES "teachers" ("id");

ALTER TABLE "course_video" ADD FOREIGN KEY ("categori_id") REFERENCES "categories" ("id");

ALTER TABLE "user_roles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");



INSERT INTO categories (name) VALUES ('fron end'), ('back end');

INSERT INTO levels (name) VALUES ('principiante'), ('medio'), ('avanzado');

INSERT INTO roles (name) VALUES ('student'), ('teacher'), ('admin');

INSERT INTO users (name, email, password, age) VALUES 
('Juan', 'juan@gmail.com', 12345678, 22), 
('Ivan', 'ivan@gmail.com', 87654321, 33),
('Alejandra', 'ale@gmail.com', 12348765, 27),
('Brenda', 'bren@gmail.com', 87651243, 45),
('Ian', 'ian@gmail.com', 12437658, 32);

INSERT INTO user_roles (user_id, role_id) VALUES (1, 1), (2, 1), (3, 2), (4, 2), (5, 2), (5, 3);

INSERT INTO teachers (user_id) VALUES (3), (4), (5);

INSERT INTO courses (title, description, level_id, teacher_id) VALUES 
('css', 'estilos de cascada', 1, 1),
('javascript', 'logica en js', 2, 1),
('react', 'react js', 2, 2),
('sql', 'bases de datos', 1, 3),
('node', 'node js', 3, 3);

INSERT INTO course_video (course_id, url, categori_id) VALUES
(1, 'https://css.net', 1),
(2, 'https://js.net', 1),
(3, 'https://react.net', 1),
(4, 'https://bases.net', 2),
(5, 'https://node.net', 2);

